import React from "react";
import Link from "next/link";
import { FileText, ArrowLeft } from "lucide-react";

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-[#030712] text-white pt-32 pb-20 px-4 font-sans relative overflow-hidden">
      
      {/* Background glow */}
      <div className="absolute top-0 left-1/4 w-[600px] h-[600px] bg-teal-500/10 rounded-full blur-[150px] pointer-events-none" />

      <div className="max-w-4xl mx-auto relative z-10">
        <Link href="/" className="inline-flex items-center gap-2 text-white/50 hover:text-white transition-colors text-sm font-bold mb-8">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>
        
        <div className="flex items-center gap-4 mb-8">
          <div className="w-12 h-12 rounded-xl bg-teal-500/20 flex items-center justify-center border border-teal-500/30">
            <FileText className="w-6 h-6 text-teal-400" />
          </div>
          <div>
            <h1 className="text-4xl md:text-5xl font-black font-sora tracking-tight">Terms of Service</h1>
            <p className="text-teal-400 font-bold mt-2">Effective Date: October 2024</p>
          </div>
        </div>

        <div className="bg-[#0A0F1D]/80 backdrop-blur-xl border border-white/10 rounded-[24px] p-8 md:p-12 space-y-8 text-white/70 leading-relaxed font-medium">
          
          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white font-sora">1. Agreement to Terms</h2>
            <p>
              By accessing or using TripPilot ("the Platform"), you agree to be bound by these Terms of Service. If you disagree with any part of the terms, then you do not have permission to access the Service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white font-sora">2. Use of Our Service</h2>
            <p>
              TripPilot provides an AI-powered travel planning interface. You agree to use the service only for lawful purposes and in a way that does not infringe the rights of, restrict or inhibit anyone else's use and enjoyment of the website.
            </p>
            <p>
              We grant you a limited, non-exclusive, non-transferable, and revocable license to use our Services.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white font-sora">3. Account Creation</h2>
            <p>
              When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.
            </p>
            <p>
              You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white font-sora">4. Third-Party Links & Affiliates</h2>
            <p>
              Our Service may contain links to third-party web sites or services that are not owned or controlled by TripPilot. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party web sites or services.
            </p>
            <p>
              TripPilot participates in affiliate marketing programs. Clicking on certain links (like hotel bookings or flight reservations) may earn us a commission at no extra cost to you.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white font-sora">5. Disclaimers</h2>
            <p>
              Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The itineraries generated by AI are suggestions and should be independently verified for accuracy, safety, and availability. TripPilot is not liable for any disruptions, losses, or injuries sustained during travel based on our generated itineraries.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-white font-sora">6. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at: <br/>
              <span className="text-white font-bold">legal@trippilot.ai</span>
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
