"use client";

import { Search, Filter, Zap, MapPin, DollarSign, Users, ChevronRight, Unlock, Star, ShieldCheck, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";

const mockMarketplaceLeads = [
  { id: "MPL-882", dest: "Maldives (Honeymoon)", budget: "₹4,50,000", pax: 2, date: "Nov 2026", source: "Travixa Organic", quality: "Premium", cost: 15, intent: "High" },
  { id: "MPL-881", dest: "Dubai Shopping Fest", budget: "₹2,20,000", pax: 3, date: "Dec 2026", source: "Instagram Ads", quality: "Standard", cost: 8, intent: "Medium" },
  { id: "MPL-879", dest: "Europe Backpacking", budget: "₹3,50,000", pax: 1, date: "Oct 2026", source: "Travixa Partner", quality: "Standard", cost: 8, intent: "Medium" },
  { id: "MPL-875", dest: "Bali Corporate Retreat", budget: "₹25,00,000", pax: 45, date: "Feb 2027", source: "LinkedIn Lead", quality: "Enterprise", cost: 45, intent: "High" },
];

export default function MarketplacePage() {
  return (
    <div className="w-full max-w-[1400px] mx-auto space-y-6 pb-10 flex flex-col xl:flex-row gap-6">
      
      {/* Main Leads Area */}
      <div className="flex-1 space-y-6">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 border-b border-white/5 pb-4">
          <div>
            <h1 className="text-2xl font-bold text-white flex items-center gap-2">
              Travixa Marketplace
            </h1>
            <p className="text-xs text-[#94A3B8] mt-1">Unlock high-intent leads generated by the Travixa ecosystem.</p>
          </div>
          <div className="flex gap-4 items-center">
            <div className="flex items-center gap-2 bg-[#020817] border border-[#F59E0B]/30 px-3 py-1.5 rounded-md">
              <Zap className="w-4 h-4 text-[#F59E0B] fill-current" />
              <span className="text-xs font-bold text-white">450 Credits</span>
              <Button className="h-6 px-2 text-[10px] font-bold bg-[#F59E0B]/10 hover:bg-[#F59E0B]/20 text-[#F59E0B] border border-[#F59E0B]/20 ml-2">
                Buy More
              </Button>
            </div>
          </div>
        </div>

        {/* Toolbar */}
        <div className="flex justify-between items-center bg-[#0B1220] p-3 rounded-md border border-white/5">
          <div className="relative w-80">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-[#94A3B8]" />
            <input 
              type="text" 
              placeholder="Search by destination or budget..." 
              className="w-full bg-[#020817] border border-white/10 rounded-md py-1.5 pl-9 pr-3 text-xs text-white placeholder:text-[#94A3B8] focus:outline-none focus:border-[#38BDF8]"
            />
          </div>
          <div className="flex gap-2">
            <Button className="h-8 text-xs font-bold bg-[#020817] hover:bg-white/5 text-white border border-white/10">
              <Filter className="w-3 h-3 mr-1.5" /> Filter Quality
            </Button>
          </div>
        </div>

        {/* Leads Table */}
        <div className="bg-[#0B1220] border border-white/5 rounded-md overflow-hidden">
          <table className="w-full text-left border-collapse whitespace-nowrap">
            <thead>
              <tr className="border-b border-white/5 text-[10px] font-bold text-[#94A3B8] uppercase tracking-widest bg-white/[0.02]">
                <th className="py-3 px-4 w-12">Lead ID</th>
                <th className="py-3 px-4">Trip Request</th>
                <th className="py-3 px-4">Quality & Intent</th>
                <th className="py-3 px-4">Source</th>
                <th className="py-3 px-4 text-right">Unlock</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/[0.02]">
              {mockMarketplaceLeads.map((lead, i) => (
                <tr key={i} className="hover:bg-white/[0.02] transition-colors group">
                  <td className="py-3 px-4 text-[10px] font-mono text-[#94A3B8]">{lead.id}</td>
                  <td className="py-3 px-4">
                    <p className="text-xs font-bold text-white mb-1.5">{lead.dest}</p>
                    <div className="flex gap-3 text-[10px] text-[#94A3B8]">
                      <span className="flex items-center gap-1"><DollarSign className="w-3 h-3 text-[#14B8A6]" /> {lead.budget}</span>
                      <span className="flex items-center gap-1"><Users className="w-3 h-3" /> {lead.pax} Pax</span>
                      <span className="flex items-center gap-1">in {lead.date}</span>
                    </div>
                  </td>
                  <td className="py-3 px-4">
                    <div className="flex flex-col gap-1.5">
                      <QualityChip quality={lead.quality} />
                      <span className={`text-[10px] font-bold flex items-center gap-1 ${lead.intent === 'High' ? 'text-[#10B981]' : 'text-[#F59E0B]'}`}>
                        <TrendingUp className="w-3 h-3" /> {lead.intent} Intent
                      </span>
                    </div>
                  </td>
                  <td className="py-3 px-4">
                    <div className="flex items-center gap-2">
                      <ShieldCheck className="w-3.5 h-3.5 text-[#38BDF8]" />
                      <span className="text-[10px] font-bold text-[#94A3B8] uppercase tracking-wider">{lead.source}</span>
                    </div>
                  </td>
                  <td className="py-3 px-4 text-right">
                    <Button className="h-8 text-[10px] font-bold bg-[#14B8A6]/10 hover:bg-[#14B8A6]/20 text-[#14B8A6] border border-[#14B8A6]/20 transition-colors">
                      <Unlock className="w-3 h-3 mr-1" /> Unlock for {lead.cost} <Zap className="w-2.5 h-2.5 ml-1 fill-current" />
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          
          <div className="p-4 border-t border-white/5 bg-[#020817] flex justify-center">
             <Button className="h-8 text-xs font-bold bg-transparent hover:bg-white/5 text-[#94A3B8] hover:text-white border border-dashed border-white/20 transition-colors">
              Load More Leads
            </Button>
          </div>
        </div>

      </div>

      {/* Right Sidebar */}
      <div className="xl:w-[320px] shrink-0 space-y-6">
        
        {/* Ad Module */}
        <div className="bg-gradient-to-br from-[#0B1220] to-[#020817] border border-white/10 rounded-md p-5 shadow-[0_0_30px_rgba(20,184,166,0.05)] relative overflow-hidden group">
          <div className="absolute top-0 right-0 w-32 h-32 bg-[#14B8A6]/10 rounded-full blur-[40px] group-hover:bg-[#14B8A6]/20 transition-colors" />
          
          <div className="w-10 h-10 rounded-lg bg-[#14B8A6]/10 border border-[#14B8A6]/30 flex items-center justify-center mb-4 relative z-10">
            <Star className="w-5 h-5 text-[#14B8A6] fill-current" />
          </div>
          
          <h2 className="text-sm font-bold text-white mb-2 relative z-10">Travixa Enterprise</h2>
          <p className="text-xs text-[#94A3B8] mb-5 leading-relaxed relative z-10">
            Get exclusive access to verified corporate retreat leads and high net-worth individuals before they hit the open marketplace.
          </p>
          
          <Button className="w-full h-9 text-xs font-bold bg-white text-[#0F172A] hover:bg-white/90 border-none relative z-10">
            Upgrade to Enterprise
          </Button>
        </div>

        {/* Marketplace Analytics */}
        <div className="bg-[#0B1220] border border-white/5 rounded-md p-5 shadow-sm">
           <h3 className="text-sm font-bold text-white mb-4">Your Marketplace ROI</h3>
           
           <div className="space-y-4">
             <div className="flex justify-between items-center pb-3 border-b border-white/5">
                <span className="text-xs text-[#94A3B8]">Leads Unlocked</span>
                <span className="text-xs font-bold text-white">42</span>
             </div>
             <div className="flex justify-between items-center pb-3 border-b border-white/5">
                <span className="text-xs text-[#94A3B8]">Credits Spent</span>
                <span className="text-xs font-bold text-[#F59E0B] flex items-center gap-1">540 <Zap className="w-3 h-3 fill-current" /></span>
             </div>
             <div className="flex justify-between items-center pb-3 border-b border-white/5">
                <span className="text-xs text-[#94A3B8]">Conversion Rate</span>
                <span className="text-xs font-bold text-[#10B981]">28.5%</span>
             </div>
             <div className="pt-2">
                <span className="text-[10px] font-bold text-[#94A3B8] uppercase tracking-widest block mb-1">Revenue Generated</span>
                <span className="text-2xl font-bold text-[#14B8A6]">₹14,20,000</span>
             </div>
           </div>
        </div>

      </div>
    </div>
  );
}

function QualityChip({ quality }: { quality: string }) {
  if (quality === "Enterprise") return <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold bg-purple-500/10 text-purple-400 border border-purple-500/20">Enterprise</span>;
  if (quality === "Premium") return <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold bg-[#F59E0B]/10 text-[#F59E0B] border border-[#F59E0B]/20">Premium</span>;
  return <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold bg-white/10 text-[#94A3B8] border border-white/20">Standard</span>;
}
